TMDT/Models/_GioHang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TMDT.Models
{
    public class _GioHang
    {
        ChoDoCuEntities db = new ChoDoCuEntities();
        public int Id { set; get; }
        public string sanpham { set; get; }
        public string hinh { set; get; }
        public Double dongia { set; get; }
        public DateTime Ngaydat { set; get; }
        public int soluong { set; get; }
        public string alias { get; set; }
        public string status { get; set; }
        public Double thanhtien
        {
            get { return soluong * dongia; }
        }
        public _GioHang(int id)
        {
            Id = id;
            Product product = db.Products.Single(n => n.idProduct == Id);
            //Category_Status sta = db.Category_Status.Single(n => n.idCate_status == Id);
            sanpham = product.nameProduct;
            hinh = product.imageProduct_1;
            dongia = double.Parse(product.priceProduct.ToString());
            soluong = 1;
            alias = product.Alias;
            //status = sta.nameStatus;
        }

        public _GioHang()
        {
        }
    }
}

TMDT/Controllers/BuyerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMDT.Models;

namespace TMDT.Controllers
{
    public class BuyerController : Controller
    {
        ChoDoCuEntities db = new ChoDoCuEntities();

        [HttpGet]
        public ActionResult DanhSachMuaHang()
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 2)) return HttpNotFound();

            int ss = Int32.Parse(Session["idAccount"].ToString());
            IList<_GioHang> infoAcc = new List<_GioHang>();
            var query = from order in db.Orders
                        join list in db.listOrders on order.idOrder equals list.idOrder
                        join pro in db.Products on list.idProduct equals pro.idProduct
                        join tt in db.Category_Status on order.Category_Status equals tt.idCate_status
                        where order.idAccount == ss && order.hideOrder == false
                        orderby order.dateOrder descending
                        select new { order, pro, tt, list };

            var infoAccs = query.ToList();
            foreach (var info in infoAccs)
            {
                infoAcc.Add(new _GioHang()
                {
                    sanpham = info.pro.nameProduct,
                    hinh = info.pro.imageProduct_1,
                    dongia = double.Parse(info.pro.priceProduct.ToString()),
                    soluong = info.list.amountProduct,
                    Ngaydat = info.order.dateOrder,
                    status = info.tt.nameStatus
                });
            }
            return View(infoAcc);
        }
        public ActionResult ThanhToan(string strUrl)
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 2)) return HttpNotFound();

            List<_GioHang> lstGiohang = Laygiohang();
            if (lstGiohang == null) return RedirectToAction("TrangChu", "Home");

            foreach (var i in lstGiohang)
            {
                var order = new Order();
                order.idAccount = Int32.Parse(Session["idAccount"].ToString());
                order.dateOrder = DateTime.Parse(DateTime.Now.ToString());
                order.Category_Status = 1;

                var listOrder = new listOrder();
                listOrder.idOrder = order.idOrder;
                listOrder.idProduct = i.Id;
                listOrder.amountProduct = i.soluong;

                db.Orders.Add(order);
                db.listOrders.Add(listOrder);

                var a = from b in db.Products
                        where b.idProduct == i.Id
                        select b;
                foreach (var c in a)
                {
                    string thongbao = "<script language='javascript' type='text/javascript'>alert('LỖI: Sản phẩm: [ " + i.sanpham + " ] trong kho chỉ còn " + c.amountProduct + " sản phẩm'); window.location.href='/gio-hang';</script>";
                    if (c.amountProduct < i.soluong)
                        return Content(thongbao);
                    c.amountProduct -= i.soluong;
                }
                db.SaveChanges();
            }
            XoaTatcaGioHang();
            return Content("<script language='javascript' type='text/javascript'>alert('Thanh toán thành công'); window.location.href='/trang-chu';</script></script>");
        }
        public List<_GioHang> Laygiohang()
        {
            List<_GioHang> lstGiohang = Session["Giohang"] as List<_GioHang>;
            if (lstGiohang == null)
            {
                lstGiohang = new List<_GioHang>();
                Session["Giohang"] = lstGiohang;
            }
            return lstGiohang;
        }
        public ActionResult ThemGiohang(int Id, string strURL, FormCollection collect)
        {
            var sl = collect["SoLuong"];
            if (String.IsNullOrEmpty(sl))
                return Content("<script language='javascript' type='text/javascript'>alert('Số lượng sản phẩm không để trống!'); window.location.href='" + strURL + "';</script>");
            List<_GioHang> lstGioHang = Laygiohang();
            _GioHang sanpham = lstGioHang.Find(n => n.Id == Id);
            if (sanpham == null)
            {
                sanpham = new _GioHang(Id);
                lstGioHang.Add(sanpham);
                if (!String.IsNullOrEmpty(sl.ToString()))
                    sanpham.soluong += Int32.Parse(sl) - 1;
            }
            else
            {
                sanpham.soluong++;
            }
            return Content("<script language='javascript' type='text/javascript'>alert('Thêm sản phẩm thành công!'); window.location.href='" + strURL + "';</script>");
        }


        public int TongSoLuong()
        {
            int TongSoLuong = 0;
            List<_GioHang> lstGiohang = Session["GioHang"] as List<_GioHang>;
            if (lstGiohang != null)
            {
                TongSoLuong = lstGiohang.Sum(n => n.soluong);
            }
            return TongSoLuong;
        }

        public double TongTien()
        {
            double Tongtien = 0;
            List<_GioHang> lstGiohang = Session["GioHang"] as List<_GioHang>;
            if (lstGiohang != null)
            {
                Tongtien = lstGiohang.Sum(n => n.thanhtien);

            }
            return Tongtien;
        }
        public ActionResult GioHang()
        {
            List<_GioHang> lstGiohang = Laygiohang();
            if (lstGiohang.Count == 0)
            {
                return RedirectToAction("TrangChu", "Home");
            }
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            return View(lstGiohang);
        }
        public ActionResult XoaGiohang(int iMaSP)
        {
            List<_GioHang> lstGiohang = Laygiohang();
            _GioHang sanpham = lstGiohang.SingleOrDefault(n => n.Id == iMaSP);
            if (sanpham != null)
            {
                lstGiohang.RemoveAll(n => n.Id == iMaSP);
                return RedirectToAction("GioHang");
            }
            if (lstGiohang.Count == 0)
            {
                return RedirectToAction("TrangChu", "Home");
            }
            return RedirectToAction("GioHang");

        }
        public ActionResult XoaTatcaGioHang()
        {
            List<_GioHang> lstGiohang = Laygiohang();
            lstGiohang.Clear();
            return RedirectToAction("TrangChu", "Home");
        }
        public ActionResult Capnhatgiohang(FormCollection collect)
        {
            List<_GioHang> lstGiohang = Laygiohang();
            var iMaSP = Int32.Parse(collect["MaSP"].ToString());
            _GioHang sanpham = lstGiohang.SingleOrDefault(n => n.Id == iMaSP);
            if (sanpham != null)
            {
                sanpham.soluong = Int32.Parse(collect["txtsoluong"].ToString());
            }
            return RedirectToAction("GioHang");

        }
        public ActionResult GioHangPartial()
        {
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            return PartialView();
        }
    }
}

TMDT/Views/Buyer/DanhSachMuaHang.cshtml
@model IEnumerable<TMDT.Models._GioHang>
@{
    ViewBag.Title = "Danh sách mua hàng";
    Layout = "~/Views/Shared/_Dashboard_1.cshtml";
}

@section styles {
    <link rel="stylesheet" href="~/Assets/_Apartment/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}
@section scripts {
    <script src="~/Assets/_Apartment/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Assets/_Apartment/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script>
        $(function () {
            $("#example1").DataTable({ "lengthMenu": [[10, 25, 50, 150, 200], [10, 25, 50, 150, 200]] }); //Cái [] ngoài cùng hiện tên vd:"Tất cả" thì = -1
        });
    </script>
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Danh sách mua hàng</h1>
                </div>
                <!-- /.col -->
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><span style="color:red"><b>Danh sách mua hàng</b></span></h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-2">
                        <table id="example1" class="table table-bordered table-striped text-nowrap">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Tên sản phẩm</th>
                                    <th>Ảnh sản phẩm</th>
                                    <th>Thành tiền</th>
                                    <th>Số lượng</th>
                                    <th>Ngày đặt</th>
                                    <th>Trạng thái</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{int i = 0; }
                                @foreach (var kh in Model)
                                {
                                    i++;
                                    <tr>
                                        <td>@i</td>
                                        <td>@Html.DisplayFor(a => kh.sanpham)</td>
                                        <td><img src="~/Assets/ImageProduct/@kh.hinh" style="width: 100px; height: 100px;"/></td>
                                        <td>@Html.DisplayFor(a => kh.dongia)</td>
                                        <td>@Html.DisplayFor(a=>kh.soluong)</td>
                                        <td>@Html.DisplayFor(a => kh.Ngaydat)</td>
                                        <td>@Html.DisplayFor(a => kh.status)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- End Main content -->
</div>

TMDT/Views/Buyer/GioHang.cshtml
@using TMDT.Models;
@model List<_GioHang>
@{
    ViewBag.Title = "Giỏ hàng";
    var money = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <!-- fontawsome  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossorigin="anonymous" />
    <!-- font gg  -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap"
          rel="stylesheet" />
    <!-- BS4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
    <!-- main css  -->
    <link rel="stylesheet" href="~/Assets/_FeGit/css/main.css" />
</head>
<body>
    <header class="card__header">
        <nav class="navbar navbar-expand-lg w-75 m-auto">
            <a href="@Url.Action("TrangChu", "Home")"><img src="~/Assets/_FeGit/img/logo.png" alt=""></a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Giỏ hàng</a>
                    </li>
                </ul>

            </div>
        </nav>
    </header>
    <section class="card w-100 m-auto">
        <!-- content -->
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-9 card__left">
                    <div style="padding-top: 10px;"></div>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Hình ảnh</th>
                                    <th scope="col">Tên sản phẩm</th>
                                    <th scope="col">Đơn giá</th>
                                    <th scope="col">Số lượng</th>
                                    <th scope="col">Thành tiền</th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            @{ int j = 0; }
                            @foreach (var item in Model)
                            {
                                j++;
                                <tbody>
                                    <tr>
                                        <th scope="row">@j</th>
                                        <td class="img"><img src="~/Assets/ImageProduct/@item.hinh" alt="" style="width: 100px; height: 100px; border-radius: 5px;"></td>
                                        <td class="tensp">@item.sanpham</td>
                                        <td class="dongia">@String.Format(money, "{0:c0}", item.dongia)</td>
                                        @using (Html.BeginForm("Capnhatgiohang", "Buyer", FormMethod.Post))
                                        {
                                            <td hidden><input type="hidden" name="MaSP" value="@item.Id" /></td>
                                            <td class="sl"><input type="number" min="1" name="txtsoluong" value="@item.soluong" style="width: 50px;" /></td>
                                            <td class="thanhtien">@String.Format(money, "{0:c0}", item.thanhtien)</td>
                                            <td> @Html.ActionLink("Xoá", "XoaGiohang", new { @iMaSp = item.Id })</td>
                                            <td> <a href="@Url.Action("ChiTietSP", "Home", new { id = item.Id, @alias = item.alias })">Chi Tiết</a></td>
                                            <td><input type="submit" value="Cập nhật" style="background-color: #f65b40; border-width: 0; color: #fff; padding: 7px; border-radius: 2px; font-weight: bold;" /></td>
                                        }
                                    </tr>
                                </tbody>
                            }
                            <tr style="font-weight:bold; color:orange;text-align:right">
                                <td colspan="10">
                                    @Html.ActionLink("Xoá Giỏ Hàng", "XoaTatcaGioHang")
                                </td>
                            </tr>
                            <tr style="font-weight: bold; text-align: right; color:red">
                                <td colspan="10">
                                    Số lượng: @ViewBag.Tongsoluong
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="col-sm-3 card__right">
                    <div style="padding-top: 10px;"></div>
                    <label class="id__user"><i class="fa fa-user icn__user "></i>Người dùng </label>
                    <form class="form-inline mt-2 search__form"></form>
                    <div class="title__hoadon my-3 text-center p-2">
                        Hóa đơn
                    </div>
                    <div class="border-bottom py-2">
                        <label class="w-50 ml-5 text-right"><b style="color: red">Tổng tiền: @String.Format(money, "{0:c0}", @ViewBag.Tongtien)</b></label>
                    </div>
                    <a href="@Url.Action("ThanhToan", "Buyer")" style="text-decoration: none;">
                        <div class="row px-3  mt-3">
                            <span class="col-sm-12 btn thanh-toan">Thanh toán</span>
                        </div>
                    </a>
                    <a href="@Url.Action("PaymentWithPaypal", "Paypal")" style="text-decoration: none;">
                        <div class="row px-3  mt-3">
                            <span class="col-sm-12 btn thanh-toan" style="background-color: #1371e5; color: #fff;"><i class="fab fa-cc-paypal"></i> Thanh toán Paypal</span>
                        </div>
                    </a>
                </div>
            </div>
            <div style="padding-top: 700px;"></div>
        </div>
    </section>
    <div style="padding-top: 50px;"></div>

    <!-- bs4  -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>
</body>
</html>

TMDT/Views/Buyer/GioHangPartial.cshtml
<li class="nav-item active">
    <a class="nav-link" href="@Url.Action("GioHang", "Buyer")"><i class="fas fa-shopping-cart"></i> Giỏ hàng (@ViewBag.Tongsoluong)</a>
</li>