TMDT/Controllers/ManagerController.cs
using Common;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMDT.Models;

namespace TMDT.Controllers
{
    public class ManagerController : Controller
    {
        ChoDoCuEntities db = new ChoDoCuEntities();

        //Danh sach san pham doi duyet//
        [HttpGet]
        public ActionResult SanPhamDangDoiDuyet()
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 4) && !Equals(Session["idRole"], 5)) return HttpNotFound();
            IList<_FullProduct> infoAcc = new List<_FullProduct>();
            var query = from cus in db.infoAccounts
                        join tt in db.Products on cus.idAccount equals tt.idAccount
                        join hihi in db.Category_Product on tt.idCategory_Product equals hihi.idCategory_Product
                        where tt.hideProduct == true && cus.idAccount == tt.idAccount && tt.confirmProduct == null
                        orderby tt.datePost descending
                        select new { cus, tt, hihi };

            var infoAccs = query.ToList();
            foreach (var info in infoAccs)
            {
                infoAcc.Add(new _FullProduct()
                {
                    idProduct = info.tt.idProduct,
                    nameProduct = info.tt.nameProduct,
                    priceProduct = info.tt.priceProduct,
                    amountProduct = info.tt.amountProduct,
                    descriptionProduct = info.tt.descriptionProduct,
                    datePost = info.tt.datePost,
                    nameCategory = info.hihi.nameCategory,
                    Fullname = info.cus.Fullname,
                    imageProduct_1 = info.tt.imageProduct_1,
                    imageProduct_2 = info.tt.imageProduct_2,
                    imageProduct_3 = info.tt.imageProduct_3,
                    imageProduct_4 = info.tt.imageProduct_4
                });
            }
            return View(infoAcc);
        }

        //Danh sach san pham duoc duyet//
        [HttpGet]
        public ActionResult SanPhamDaDuyet()
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 4) && !Equals(Session["idRole"], 5)) return HttpNotFound();
            IList<_FullProduct> infoAcc = new List<_FullProduct>();
            var query = from cus in db.infoAccounts
                        join tt in db.Products on cus.idAccount equals tt.idAccount
                        join hihi in db.Category_Product on tt.idCategory_Product equals hihi.idCategory_Product
                        where tt.hideProduct == false && cus.idAccount == tt.idAccount
                        orderby tt.datePost descending
                        select new { cus, tt, hihi };

            var infoAccs = query.ToList();
            foreach (var info in infoAccs)
            {
                infoAcc.Add(new _FullProduct()
                {
                    idProduct = info.tt.idProduct,
                    nameProduct = info.tt.nameProduct,
                    priceProduct = info.tt.priceProduct,
                    amountProduct = info.tt.amountProduct,
                    descriptionProduct = info.tt.descriptionProduct,
                    datePost = info.tt.datePost,
                    nameCategory = info.hihi.nameCategory,
                    Fullname = info.cus.Fullname,
                    imageProduct_1 = info.tt.imageProduct_1,
                    imageProduct_2 = info.tt.imageProduct_2,
                    imageProduct_3 = info.tt.imageProduct_3,
                    imageProduct_4 = info.tt.imageProduct_4
                });
            }
            return View(infoAcc);
        }
        //Duyet san pham//
        public ActionResult DuyetSanPham()
        {
            var getid = Url.RequestContext.RouteData.Values["id"];
            int g = Int32.Parse(getid.ToString());
            var a = from b in db.Products
                    join h in db.Logins on b.idAccount equals h.idAccount
                    where b.idProduct == g && b.hideProduct == true
                    select new { b, h };
            foreach (var d in a)
            {
                d.b.hideProduct = false;
                d.b.confirmProduct = true;
                string content = System.IO.File.ReadAllText(Server.MapPath("~/Assets/SendMail/DuyetSanPham.html"));
                content = content.Replace("{{idproduct}}", d.b.idProduct.ToString());
                new MailHelper().SendMail(d.h.Email, "[No Reply] Tình Trạng Sản Phẩm", content);
            }
            db.SaveChanges();
            return RedirectToAction("SanPhamDangDoiDuyet");
        }
        //Tu choi san pham//
        public ActionResult TuChoiSanPham()
        {
            var getid = Url.RequestContext.RouteData.Values["id"];
            int g = Int32.Parse(getid.ToString());
            var a = from b in db.Products
                    join h in db.Logins on b.idAccount equals h.idAccount
                    where b.idProduct == g && b.hideProduct == true
                    select new { b, h };
            foreach (var d in a)
            {
                d.b.hideProduct = true;
                d.b.confirmProduct = false;
                string content = System.IO.File.ReadAllText(Server.MapPath("~/Assets/SendMail/TuChoiSanPham.html"));
                content = content.Replace("{{idproduct}}", d.b.idProduct.ToString());
                new MailHelper().SendMail(d.h.Email, "[No Reply] Tình Trạng Sản Phẩm", content);
            }
            db.SaveChanges();
            return RedirectToAction("SanPhamDangDoiDuyet");
        }
        [NonAction]
        public void DropDownListChucVu()
        {
            var dataList = new SelectList(
                            (
                                from position in db.Roles
                                where position.groupRole == 2
                                select new SelectListItem { Text = position.nameRole, Value = position.idRole.ToString() }
                            ), "Value", "Text");
            ViewBag.Loadchucvu = dataList;
        }
        // GET: Manager
        //Quản lý khách hàng//
        [HttpGet]
        public ActionResult QuanLyTaiKhoanKH()
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 4) && !Equals(Session["idRole"], 5)) return HttpNotFound();
            IList<_FullAccountInfo> infoAcc = new List<_FullAccountInfo>();
            var query = from acc in db.infoAccounts
                        join lg in db.Logins on acc.idAccount equals lg.idAccount
                        join role in db.Roles on acc.idRole equals role.idRole
                        where role.groupRole == 1 && lg.hideAcc == false
                        orderby lg.idAccount descending
                        select new { acc, lg, role };

            var infoAccs = query.ToList();
            foreach (var info in infoAccs)
            {
                infoAcc.Add(new _FullAccountInfo()
                {
                    idAccount = info.lg.idAccount,
                    Fullname = info.acc.Fullname,
                    Email = info.lg.Email,
                    Birthday = info.acc.Birthday,
                    Address = info.acc.Address,
                    PhoneNumber = info.acc.PhoneNumber,
                    ChucVu = info.role.nameRole
                });
            }
            return View(infoAcc);
        }

        //Quản lý nhân viên//
        [HttpGet]
        public ActionResult QuanLyNhanVien()
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 5)) return HttpNotFound();
            IList<_FullAccountInfo> infoAcc = new List<_FullAccountInfo>();
            var query = from acc in db.infoAccounts
                        join lg in db.Logins on acc.idAccount equals lg.idAccount
                        join role in db.Roles on acc.idRole equals role.idRole
                        where role.groupRole == 2 && lg.hideAcc == false
                        orderby lg.idAccount descending
                        select new { acc, lg, role };

            var infoAccs = query.ToList();
            foreach (var info in infoAccs)
            {
                infoAcc.Add(new _FullAccountInfo()
                {
                    idAccount = info.lg.idAccount,
                    Fullname = info.acc.Fullname,
                    Email = info.lg.Email,
                    Birthday = info.acc.Birthday,
                    Address = info.acc.Address,
                    PhoneNumber = info.acc.PhoneNumber,
                    ChucVu = info.role.nameRole,
                });
            }
            return View(infoAcc);
        }
        //Danh muc san pham//
        public ActionResult DanhMucSanPham()
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 5)) return HttpNotFound();
            var query = from acc in db.Category_Product
                        select acc;
            return View(query.ToList());
        }
        [HttpGet]
        public ActionResult ThemDanhMuc()
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 5)) return HttpNotFound();
            return View();
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult ThemDanhMuc(FormCollection collection, HttpPostedFileBase imageCategory)
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 5)) return HttpNotFound();

TMDT/Views/Manager/CapNhatDanhMuc.cshtml
@model IEnumerable<TMDT.Models.Category_Product>

@{
    ViewBag.Title = "Cập Nhật Danh Mục";
    Layout = "~/Views/Shared/_Dashboard_1.cshtml";
}
@section styles {
    <link rel="stylesheet" href="~/Assets/_Apartment/dist/css/hide-arrow-number.css">
}
@section scripts {
    <!-- jquery ASP.NET -->
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Assets/_Apartment/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            bsCustomFileInput.init();
        });</script>
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Cập nhật danh mục</h1>
                </div>
                <!-- /.col -->
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="card">
                <div class="card-body register-card-body">
                    <p class="login-box-msg">
                        <b>CẬP NHẬT DANH MỤC</b>
                    </p>
                    @using (Html.BeginForm("CapNhatDanhMuc", "Manager", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        <p><span style="color:Highlight">@ViewData["Err4"]</span></p>
                        foreach (var tt in Model)
                        {
                            <label>Mã danh mục</label>
                            <div class="input-group mb-3">
                                @Html.TextBox("id", null, new { @class = "form-control", type = "text", placeholder = "Mã danh mục", Value = tt.idCategory_Product })
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-user"></span>
                                    </div>
                                </div>
                            </div>
                            <label>Tên danh mục</label>
                            <div class="input-group mb-3">
                                @Html.TextBox("name", null, new { @class = "form-control", type = "text", placeholder = "Tên danh mục", Value = tt.nameCategory })
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-user"></span>
                                    </div>
                                </div>
                            </div>
                            <label for="avartar">Ảnh danh mục</label>
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="imageCategory" accept="image/*" name="imageCategory">
                                <label class="custom-file-label text-muted" for="avartar">Ảnh danh mục</label>
                            </div>
                            <label>Icon</label>
                            <div class="input-group mb-3">
                                @Html.TextBox("icon", null, new { @class = "form-control", type = "text", placeholder = "Icon danh mục", Value = tt.iconCategory })
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-user"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <!-- /.col -->
                                <div class="col-md-auto">
                                    <button type="submit" class="btn btn-primary btn-block" name="updateAccount" value="updateAccount" onclick="return confirm('Bạn có chắc muốn cập nhật danh mục này ?')">Cập nhật</button>
                                </div>
                                <!-- /.col -->
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
</div>

TMDT/Views/Manager/CapNhatKhachHang.cshtml
@model IEnumerable<TMDT.Models._FullAccountInfo>

@{
    ViewBag.Title = "Cập Nhật Khách Hàng";
    Layout = "~/Views/Shared/_Dashboard_1.cshtml";
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Cập nhật khách hàng</h1>
                </div>
                <!-- /.col -->
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="card">
                <div class="card-body register-card-body">
                    <p class="login-box-msg">
                        <b>CẬP NHẬT KHÁCH HÀNG</b>
                    </p>
                    @using (Html.BeginForm("CapNhatKhachHang", "Manager", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        <p><span style="color:Highlight">@ViewData["Err3"]</span></p>
                            <p><span style="color:red">@ViewData["Err1"]</span></p>
                            <p><span style="color:red">@ViewData["ErrMess1"]</span></p>
                            <p><span style="color:red">@ViewData["ErrMess2"]</span></p>
                            <p><span style="color:red">@ViewData["ErrMess3"]</span></p>
                            <p><span style="color:red">@ViewData["ErrMess4"]</span></p>
                            <p><span style="color:red">@ViewData["ErrMess5"]</span></p>
                        foreach (var tt in Model)
                        {
                            <label>Họ tên</label>
                                <div class="input-group mb-3">
                                    @Html.TextBox("Username", null, new { @class = "form-control", type = "text", placeholder = "Họ và tên", Value = tt.Fullname })
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-user"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    @Html.TextBox("Birthday", null, new { @class = "form-control", type = "date", name = "Birthday", Value = Convert.ToDateTime(tt.Birthday).ToString("yyyy-MM-dd") })
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-birthday-cake"></span>
                                        </div>
                                    </div>
                                </div>
                            /* <label>Giới tính:</label><text>&nbsp;&nbsp;&nbsp;&nbsp;</text>
                             if (tt.Sex.ToString() == "Nam")
                             {
                                 <label class="radio-inline">
                                     @Html.RadioButton("Sex", "Nam", new { Checked = "checked" }) Nam
                                 </label><text>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</text>
                                 <label class="radio-inline">
                                     @Html.RadioButton("Sex", "Nữ") Nữ
                                 </label><p></p>
                             }
                             else
                             {
                                 <label class="radio-inline">
                                     @Html.RadioButton("Sex", "Nam") Nam
                                 </label><text>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</text>
                                 <label class="radio-inline">
                                     @Html.RadioButton("Sex", "Nữ", new { Checked = "checked" }) Nữ
                                 </label><p></p>
                             }*/
                            <div class="input-group mb-3">
                                @Html.TextBox("PhoneNumber", null, new { @class = "form-control", type = "number", placeholder = "Số điện thoại", Value = tt.PhoneNumber })
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fas fa-phone"></span>
                                    </div>
                                </div>
                            </div>
                                <label>Địa chỉ</label>
                                <div class="input-group mb-3">
                                    @Html.TextBox("Address", null, new { @class = "form-control", type = "text", placeholder = "Địa chỉ", Value = tt.Address })
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-id-card"></span>
                                        </div>
                                    </div>
                                </div>
                                <label>Địa chỉ Email</label>
                                <div class="input-group mb-3">
                                    @Html.TextBox("Email", null, new { @class = "form-control", type = "email", placeholder = "Địa chỉ Email", Value = tt.Email })
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-envelope"></span>
                                        </div>
                                    </div>
                                </div>
                               /* <label>Chức vụ</label>
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" value="@Html.DisplayFor(a => tt.ChucVu)" disabled>
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-briefcase"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    @Html.DropDownList("idStaff", ViewBag.Loadchucvu as SelectList, "Chọn chức vụ (nếu cần thay đổi)", new { @class = "form-control" })
                                    <div class="input-group-text">
                                        <span class="fas fa-briefcase"></span>
                                    </div>
                                </div>*/
                        }
                        <div class="row">
                            <!-- /.col -->
                            <div class="col-md-auto">
                                <button type="submit" class="btn btn-primary btn-block" name="updateAccount" value="updateAccount" onclick="return confirm('Bạn có chắc muốn cập nhật tài khoản này ?')">Cập nhật</button>
                            </div>
                            <!-- /.col -->
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
</div>

TMDT/Views/Manager/CapNhatNhanVien.cshtml
@model IEnumerable<TMDT.Models._FullAccountInfo>

@{
    ViewBag.Title = "Cập Nhật Nhân Viên";
    Layout = "~/Views/Shared/_Dashboard_1.cshtml";
}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Cập nhật nhân viên</h1>
                    </div>
                    <!-- /.col -->
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <div class="card">
                    <div class="card-body register-card-body">
                        <p class="login-box-msg">
                            <b>CẬP NHẬT NHÂN VIÊN</b>
                        </p>
                        @using (Html.BeginForm("CapNhatNhanVien", "Manager", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            <p><span style="color:Highlight">@ViewData["Err2"]</span></p>
                            <p><span style="color:red">@ViewData["Err1"]</span></p>
                            <p><span style="color:red">@ViewData["ErrMess1"]</span></p>
                            <p><span style="color:red">@ViewData["ErrMess2"]</span></p>
                            <p><span style="color:red">@ViewData["ErrMess3"]</span></p>
                            <p><span style="color:red">@ViewData["ErrMess4"]</span></p>
                            <p><span style="color:red">@ViewData["ErrMess5"]</span></p>
                            foreach (var tt in Model)
                            {
                                <label>Họ tên</label>
                                <div class="input-group mb-3">
                                    @Html.TextBox("Username", null, new { @class = "form-control", type = "text", placeholder = "Họ và tên", Value = tt.Fullname })
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-user"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    @Html.TextBox("Birthday", null, new { @class = "form-control", type = "date", name = "Birthday", Value = Convert.ToDateTime(tt.Birthday).ToString("yyyy-MM-dd") })
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-birthday-cake"></span>
                                        </div>
                                    </div>
                                </div>
                                /* <label>Giới tính:</label><text>&nbsp;&nbsp;&nbsp;&nbsp;</text>
                                 if (tt.Sex.ToString() == "Nam")
                                 {
                                     <label class="radio-inline">
                                         @Html.RadioButton("Sex", "Nam", new { Checked = "checked" }) Nam
                                     </label><text>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</text>
                                     <label class="radio-inline">
                                         @Html.RadioButton("Sex", "Nữ") Nữ
                                     </label><p></p>
                                 }
                                 else
                                 {
                                     <label class="radio-inline">
                                         @Html.RadioButton("Sex", "Nam") Nam
                                     </label><text>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</text>
                                     <label class="radio-inline">
                                         @Html.RadioButton("Sex", "Nữ", new { Checked = "checked" }) Nữ
                                     </label><p></p>
                                 }*/
                                <div class="input-group mb-3">
                                    @Html.TextBox("PhoneNumber", null, new { @class = "form-control", type = "number", placeholder = "Số điện thoại", Value = tt.PhoneNumber })
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fas fa-phone"></span>
                                        </div>
                                    </div>
                                </div>
                                <label>Địa chỉ</label>
                                <div class="input-group mb-3">
                                    @Html.TextBox("Address", null, new { @class = "form-control", type = "text", placeholder = "Địa chỉ", Value = tt.Address })
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-id-card"></span>
                                        </div>
                                    </div>
                                </div>
                                <label>Địa chỉ Email</label>
                                <div class="input-group mb-3">
                                    @Html.TextBox("Email", null, new { @class = "form-control", type = "email", placeholder = "Địa chỉ Email", Value = tt.Email })
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-envelope"></span>
                                        </div>
                                    </div>
                                </div>
                                <label>Chức vụ</label>
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" value="@Html.DisplayFor(a => tt.ChucVu)" disabled>
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-briefcase"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    @Html.DropDownList("idStaff", ViewBag.Loadchucvu as SelectList, "Chọn chức vụ (nếu cần thay đổi)", new { @class = "form-control" })
                                    <div class="input-group-text">
                                        <span class="fas fa-briefcase"></span>
                                    </div>
                                </div>
                            }
                            <div class="row">
                                <!-- /.col -->
                                <div class="col-md-auto">
                                    <button type="submit" class="btn btn-primary btn-block" name="updateAccount" value="updateAccount" onclick="return confirm('Bạn có chắc muốn cập nhật tài khoản này ?')">Cập nhật</button>
                                </div>
                                <!-- /.col -->
                            </div>
                        }
                    </div>
                </div>
            </div>
            <!-- /.card -->
        </section>
    </div>