TMDT/Controllers/ShipperController.cs
using Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMDT.Models;

namespace TMDT.Controllers
{
    public class ShipperController : Controller
    {
        ChoDoCuEntities db = new ChoDoCuEntities();
        // GET: Shipper
        [HttpGet]
        public ActionResult DonVanChuyen()
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 3)) return HttpNotFound();
            int ss = Int32.Parse(Session["idAccount"].ToString());
            IList<_GioHang> infoAcc = new List<_GioHang>();
            var query = from acc in db.infoAccounts
                        join order in db.Orders on acc.idAccount equals order.idAccount
                        join list in db.listOrders on order.idOrder equals list.idOrder
                        join pro in db.Products on list.idProduct equals pro.idProduct
                        join ship in db.listShips on order.idOrder equals ship.idOrder
                        join tt in db.Category_Status on order.Category_Status equals tt.idCate_status
                        where order.Category_Status == 2  && order.hideOrder == false && ship.confirmShip ==true
                        orderby order.dateOrder descending
                        select new { order, pro, tt, acc };

            var infoAccs = query.ToList();
            foreach (var info in infoAccs)
            {
                infoAcc.Add(new _GioHang()
                {
                    Id = info.order.idOrder,
                    sanpham = info.pro.nameProduct,
                    hinh = info.pro.imageProduct_1,
                    dongia = double.Parse(info.pro.priceProduct.ToString()),
                    soluong = 1,
                    Ngaydat = info.order.dateOrder,                   
                });
            }
            return View(infoAcc);
        }
        public ActionResult NhanShip()
        {
            var getid = Url.RequestContext.RouteData.Values["id"];
            int ss = Int32.Parse(getid.ToString());
            int g = Int32.Parse(getid.ToString());
            var a = from b in db.Orders
                    join h in db.Logins on b.idAccount equals h.idAccount
                    join tt in db.Category_Status on b.Category_Status equals tt.idCate_status
                    join vc in db.listShips on b.idOrder equals vc.idOrder
                    where b.idOrder == g && b.Category_Status == 2 && b.hideOrder == false
                    select vc;
            foreach (var d in a)
            {               
                d.confirmShip = false;
            }
            db.SaveChanges();
            return RedirectToAction("DonVanChuyen");
        }
        [HttpGet]
        public ActionResult DonVanChuyenDaNhan()
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 3)) return HttpNotFound();
            int ss = Int32.Parse(Session["idAccount"].ToString());
            IList<_GioHang> infoAcc = new List<_GioHang>();
            var query = from acc in db.infoAccounts
                        join order in db.Orders on acc.idAccount equals order.idAccount
                        join list in db.listOrders on order.idOrder equals list.idOrder
                        join pro in db.Products on list.idProduct equals pro.idProduct
                        join tt in db.Category_Status on order.Category_Status equals tt.idCate_status
                        join ship in db.listShips on order.idOrder equals ship.idOrder
                        where order.Category_Status == 2 && acc.idAccount == ss && order.hideOrder == false && ship.confirmShip==false
                        orderby order.dateOrder descending
                        select new { order, pro, tt, acc };

            var infoAccs = query.ToList();
            foreach (var info in infoAccs)
            {
                infoAcc.Add(new _GioHang()
                {
                    Id = info.order.idOrder,
                    sanpham = info.pro.nameProduct,
                    hinh = info.pro.imageProduct_1,
                    dongia = double.Parse(info.pro.priceProduct.ToString()),
                    soluong = 1,
                    Ngaydat = info.order.dateOrder,              
                });
            }
            return View(infoAcc);
        }
        public ActionResult ThatBai()
        {
            var getid = Url.RequestContext.RouteData.Values["id"];
            int g = Int32.Parse(getid.ToString());
            var a = from b in db.Orders
                    join h in db.Logins on b.idAccount equals h.idAccount
                    join tt in db.Category_Status on b.Category_Status equals tt.idCate_status
                    join vc in db.listShips on b.idOrder equals vc.idOrder
                    where b.idOrder == g && b.Category_Status == 2 && b.hideOrder == false
                    select new { b,h,tt,vc};
            foreach (var d in a)
            {
                d.vc.Category_Status = 4;
                d.b.Category_Status = 4;        
                d.vc.hideShip = true;
                string content = System.IO.File.ReadAllText(Server.MapPath("~/Assets/SendMail/ShipThatBai.html"));
                content = content.Replace("{{idorder}}", d.b.idOrder.ToString());
                new MailHelper().SendMail(d.h.Email, "[No Reply] Tình Trạng Đơn Hàng", content);
            }
            db.SaveChanges();
            return RedirectToAction("DonVanChuyenDaNhan");
        }
        public ActionResult ThanhCong()
        {
            var getid = Url.RequestContext.RouteData.Values["id"];           
            int g = Int32.Parse(getid.ToString());
            var a = from b in db.Orders
                    join h in db.Logins on b.idAccount equals h.idAccount
                    join tt in db.Category_Status on b.Category_Status equals tt.idCate_status
                    join vc in db.listShips on b.idOrder equals vc.idOrder
                    join c in db.listOrders on b.idOrder equals c.idOrder
                    join z in db.Products on c.idProduct equals z.idProduct
                    where b.idOrder == g && b.Category_Status == 2 && b.hideOrder == false
                    select new { b, h, tt, vc ,z,c};
            foreach (var d in a)
            {
                listSell list = new listSell();
                list.idProduct = d.z.idProduct;
                list.dateSell = DateTime.Now;
                list.idAccount_Buy = d.b.idAccount;
                list.amountProduct = d.c.amountProduct;
                db.listSells.Add(list);
                d.vc.Category_Status = 3;
                d.b.Category_Status = 3;
                d.vc.confirmShip =true;
                string content = System.IO.File.ReadAllText(Server.MapPath("~/Assets/SendMail/ShipThanhCong.html"));
                content = content.Replace("{{idorder}}", d.b.idOrder.ToString());
                new MailHelper().SendMail(d.h.Email, "[No Reply] Tình Trạng Đơn Hàng", content);
            }
            db.SaveChanges();
            return RedirectToAction("DonVanChuyenDaNhan");
        }
    }
}

TMDT/Views/Shipper/DonVanChuyen.cshtml
@model IEnumerable<TMDT.Models._GioHang>
@{
    ViewBag.Title = "Danh sách đơn vận chuyển";
    Layout = "~/Views/Shared/_Dashboard_1.cshtml";
}

@section styles {
    <link rel="stylesheet" href="~/Assets/_Apartment/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}
@section scripts {
    <script src="~/Assets/_Apartment/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Assets/_Apartment/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script>
        $(function () {
            $("#example1").DataTable({ "lengthMenu": [[10, 25, 50, 150, 200], [10, 25, 50, 150, 200]] }); //Cái [] ngoài cùng hiện tên vd:"Tất cả" thì = -1
        });
    </script>
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Đơn vận chuyển</h1>
                </div>
                <!-- /.col -->
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><span style="color:red"><b>Danh sách đơn vận chuyển</b></span></h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-2">
                        <table id="example1" class="table table-bordered table-striped text-nowrap">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Tên sản phẩm</th>
                                    <th>Ảnh sản phẩm</th>
                                    <th>Thành tiền</th>
                                    <th>Số lượng</th>
                                    <th>Ngày đặt</th>
                                    <th></th>        
                                </tr>
                            </thead>
                            <tbody>
                                @{int i = 0; }
                                @foreach (var kh in Model)
                                {
                                    i++;
                                    <tr>
                                        <td>@i</td>
                                        <td>@Html.DisplayFor(a => kh.sanpham)</td>
                                        <td><img src="~/Assets/ImageProduct/@kh.hinh" style="width: 100px; height: 100px;" /></td>
                                        <td>@Html.DisplayFor(a => kh.dongia)</td>
                                        <td>@Html.DisplayFor(a => kh.soluong)</td>
                                        <td>@Html.DisplayFor(a => kh.Ngaydat)</td>
                                        <td><a href="@Url.Action("NhanShip", "Shipper", new { id = kh.Id })"><i onclick="return confirm('Bạn có chắc muốn nhận đơn hàng này ?')">Nhận</i></a></td>                         
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- End Main content -->
</div>

TMDT/Views/Shipper/DonVanChuyenDaNhan.cshtml
@model IEnumerable<TMDT.Models._GioHang>
@{
    ViewBag.Title = "Danh sách đơn vận chuyển đã nhận";
    Layout = "~/Views/Shared/_Dashboard_1.cshtml";
}

@section styles {
    <link rel="stylesheet" href="~/Assets/_Apartment/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}
@section scripts {
    <script src="~/Assets/_Apartment/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Assets/_Apartment/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script>
        $(function () {
            $("#example1").DataTable({ "lengthMenu": [[10, 25, 50, 150, 200], [10, 25, 50, 150, 200]] }); //Cái [] ngoài cùng hiện tên vd:"Tất cả" thì = -1
        });
    </script>
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Đơn vận chuyển đã nhận</h1>
                </div>
                <!-- /.col -->
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><span style="color:red"><b>Danh sách đơn vận chuyển đã nhận</b></span></h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-2">
                        <table id="example1" class="table table-bordered table-striped text-nowrap">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Tên sản phẩm</th>
                                    <th>Ảnh sản phẩm</th>
                                    <th>Thành tiền</th>
                                    <th>Số lượng</th>
                                    <th>Ngày đặt</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @{int i = 0; }
                                @foreach (var kh in Model)
                                {
                                    i++;
                                    <tr>
                                        <td>@i</td>
                                        <td>@Html.DisplayFor(a => kh.sanpham)</td>
                                        <td><img src="~/Assets/ImageProduct/@kh.hinh" style="width: 100px; height: 100px;" /></td>
                                        <td>@Html.DisplayFor(a => kh.dongia)</td>
                                        <td>@Html.DisplayFor(a => kh.soluong)</td>
                                        <td>@Html.DisplayFor(a => kh.Ngaydat)</td>
                                        <td><a href="@Url.Action("ThanhCong", "Shipper", new { id = kh.Id })"><i onclick="return confirm('Bạn có chắc muốn cập nhật đơn hàng này ?')">Thành công</i></a></td>
                                        <td><a href="@Url.Action("ThatBai", "Shipper", new { id = kh.Id })"><i onclick="return confirm('Bạn có chắc muốn cập nhật đơn hàng này ?')">Thất bại</i></a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- End Main content -->
</div>