TMDT/Controllers/RegisterAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMDT.Models;
using TMDT.Function;

namespace TMDT.Controllers
{
    public class RegisterAccountController : Controller
    {
        ChoDoCuEntities db = new ChoDoCuEntities();
        [HttpGet]
        public ActionResult ThemNhanVien()
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 5)) return HttpNotFound();
            DropDownListChucVu();
            return View();
        }
        [HttpPost]
        public ActionResult ThemNhanVien(FormCollection collection)
        {
            if (Session["idAccount"] == null) return RedirectToAction("DangNhap", "Login");
            if (!Equals(Session["idRole"], 5)) return HttpNotFound();
            DropDownListChucVu();
            var hoten = collection["Fullname"];
            var ngaysinh = String.Format("{0:dd/MM/yyy}", collection["Birthday"]);
            var mail = collection["Email"];
            var sdt = collection["Phonenumber"];
            var mk = collection["Password"];
            var mk1 = collection["Password1"];
            var chucvu = collection["idRole"];
            var dc = collection["Address"];

            var csdt = from lg in db.Logins
                       join acc in db.infoAccounts on lg.idAccount equals acc.idAccount
                       where acc.PhoneNumber == sdt || lg.Email == mail
                       select new { lg, acc };
            foreach (var checksdt in csdt)
            {
                if (checksdt.acc.PhoneNumber == sdt)
                {
                    ViewData["Err1"] = "Số điện thoại này đã tồn tại trong hệ thống!";
                    return View();
                }
                else if (checksdt.lg.Email == mail)
                {
                    ViewData["Err1"] = "Email này đã tồn tại trong hệ thống!";
                    return View();
                }
                else return View();
            }
            if (String.IsNullOrEmpty(hoten))
                ViewData["Err1"] = "Vui lòng nhập Họ tên!";
            else if (String.IsNullOrEmpty(chucvu))
                ViewData["Err1"] = "VUi lòng chọn Chức vụ!!";
            else if (String.IsNullOrEmpty(ngaysinh))
                ViewData["Err1"] = "Vui lòng nhập Ngày sinh!";
            else if (String.IsNullOrEmpty(mail))
                ViewData["Err1"] = "Vui lòng nhập Địa chỉ Email!";
            else if (String.IsNullOrEmpty(sdt))
                ViewData["Err1"] = "Vui lòng nhập Số điện thoại!";
            else if (String.IsNullOrEmpty(dc))
                ViewData["Err1"] = "Vui lòng nhập Địa chỉ!";
            else if (String.IsNullOrEmpty(mk))
                ViewData["Err1"] = "Vui lòng nhập Mật khẩu!";
            else if (mk != mk1)
                ViewData["Err1"] = "Mật khẩu nhập lại không đúng!";
            else
            {
                infoAccount info = new infoAccount();
                Login dn = new Login();

                dn.Email = mail;
                info.PhoneNumber = sdt;
                dn.Password = _Function.md5(mk);
                dn.hideAcc = false;
                db.Logins.Add(dn);
                db.SaveChanges();
                var add = from lg in db.Logins
                          where lg.Email == mail
                          select lg.idAccount;
                foreach (var c in add)
                {
                    info.idAccount = c;
                    info.Fullname = hoten;
                    info.Birthday = DateTime.Parse(ngaysinh);
                    info.idRole = Int32.Parse(chucvu);
                    info.Address = dc;
                    db.infoAccounts.Add(info);
                }
                db.SaveChanges();
                ViewData["Reg1"] = "Đăng ký thành công!";
                return View();
            }
            return View();
        }
        // GET: RegisterAccount
        [HttpGet]
        public ActionResult DangKyKhachHang()
        {
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult DangKyKhachHang(FormCollection collect, Login login, infoAccount infoAcc)
        {
            var Email = collect["Email"];
            var Hoten = collect["Hoten"];
            var Birthday = String.Format("{0:MM/dd/yyy}", collect["Birthday"]);
            var PhoneNumber = collect["PhoneNumber"];
            var Address = collect["Address"];
            var idRole = collect["idRole"];
            var MatKhau = collect["Password"];

            if (String.IsNullOrEmpty(Email))
                ViewData["Err"] = "(*) Vui lòng nhập Địa chỉ email";
            else if (String.IsNullOrEmpty(Hoten))
                ViewData["Err"] = "(*) Vui lòng nhập Họ tên";
            else if (String.IsNullOrEmpty(Birthday))
                ViewData["Err"] = "(*) Vui lòng nhập Ngày sinh";
            else if (String.IsNullOrEmpty(PhoneNumber))
                ViewData["Err"] = "(*) Vui lòng nhập Số điện thoại";
            else if (String.IsNullOrEmpty(Address))
                ViewData["Err"] = "(*) Vui lòng nhập Địa chỉ";
            else if (String.IsNullOrEmpty(MatKhau))
                ViewData["Err"] = "(*) Vui lòng nhập Mật khẩu";
            else if (String.IsNullOrEmpty(idRole))
                ViewData["Err"] = "(*) Vui lòng chọn Người bán hoặc Người mua";
            else
            {
                login.Email = Email;
                login.Password = _Function.md5(MatKhau);
                db.Logins.Add(login);

                infoAcc.Fullname = Hoten;
                infoAcc.Birthday = DateTime.Parse(Birthday);
                infoAcc.PhoneNumber = PhoneNumber;
                infoAcc.Address = Address;
                infoAcc.idRole = int.Parse(idRole);
                infoAcc.idAccount = login.idAccount;
                db.infoAccounts.Add(infoAcc);

                db.SaveChanges();

                ViewData["Err"] = "(*) ĐĂNG KÝ THÀNH CÔNG";
                return View();
            }
            return View();
        }
        [NonAction]
        public void DropDownListChucVu()
        {
            var dataList = new SelectList(
                            (
                                from position in db.Roles
                                where position.groupRole == 2
                                select new SelectListItem { Text = position.nameRole, Value = position.idRole.ToString() }
                            ), "Value", "Text");
            ViewBag.Loadchucvu = dataList;
        }
    }
}

TMDT/Views/RegisterAccount/DangKyKhachHang.cshtml
@model IEnumerable<TMDT.Models.infoAccount>
@{
    ViewBag.Title = "Đăng ký";
    Layout = "~/Views/Shared/_LanAnh.cshtml";
}
@section styles {
    <link rel="stylesheet" href="~/Assets/_Apartment/dist/css/hide-arrow-number.css">
}
<div class="register__form">
    <h1>Đăng ký tài khoản</h1>
    <div class="register__content">
        @using (Html.BeginForm("DangKyKhachHang", "RegisterAccount", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <p><span style="color:red">@ViewData["Err"]</span></p>
            <div class="form-group">
                <label for="exampleInputEmail2">Email</label>
                @Html.TextBox("Email", null, new { @class = "form-control", type = "email", id = "exampleInputEmail1", placeholder = "Email" })
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Họ tên</label>
                @Html.TextBox("Hoten", null, new { @class = "form-control", type = "text", placeholder = "Họ tên" })
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Ngày sinh</label>
                @Html.TextBox("Birthday", null, new { @class = "form-control", type = "date" })
            </div>
            <div class="form-group">
                <label for="examplePhoneNumber1">Số điện thoại</label>
                @Html.TextBox("PhoneNumber", null, new { @class = "form-control", type = "number", placeholder = "Số điện thoại" })
            </div>
            <div class="form-group">
                <label for="exampleAddress1">Địa Chỉ</label>
                @Html.TextBox("Address", null, new { @class = "form-control", type = "text", placeholder = "Địa chỉ" })
            </div>
            <div class="form-group">
                <label for="exampleInputPassword2">Mật Khẩu</label>
                @Html.TextBox("Password", null, new { @class = "form-control", type = "password", placeholder = "Mật khẩu" })
            </div>
            
            <div class="form-group">
                <label>Bạn là</label>
                <div class="form-check">
                    @Html.RadioButton("idRole", 1) Người bán<p></p>
                    @Html.RadioButton("idRole", 2) Người mua
                </div>
            </div>
            <button type="submit" class="btn btn-primary w-100 btn__regis">Đăng Ký</button>
            <p class="thoathuan">
                Bằng việc đăng ký, bạn đồng ý với <a href="">Thỏa thuận dịch vụ</a> của
                chúng tôi
                và xác nhận rằng thông tin bạn cung cấp đã hoàn chỉnh và chính xác.
            </p>
        }
    </div>
</div>

TMDT/Views/RegisterAccount/ThemNhanVien.cshtml
@{
    ViewBag.Title = "Thêm nhân viên";
    Layout = "~/Views/Shared/_Dashboard_1.cshtml";
}

@section styles {
    <link rel="stylesheet" href="~/Assets/_Apartment/dist/css/hide-arrow-number.css">
}
@section scripts {
    <!-- jquery ASP.NET -->
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Assets/_Apartment/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            bsCustomFileInput.init();
        });</script>
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Thêm nhân viên</h1>
                </div>
                <!-- /.col -->
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body register-card-body">
                    <p class="login-box-msg">
                        <b>THÊM NHÂN VIÊN</b>
                    </p>
                    @using (Html.BeginForm("ThemNhanVien", "RegisterAccount", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        <p><span style="color:red">@ViewData["Err1"]</span></p>
                        <p><span style="color:Highlight"><b>@ViewData["Reg1"]</b></span></p>
                        @*<p><span style="color:Highlight"><b>@ViewData["Reg1"]</b></span></p>
                            <p><span style="color:Highlight"><b>@ViewData["Reg2"]</b></span></p>
                            <p><span style="color:Highlight"><b>@ViewData["Reg3"]</b></span></p>*@
                        <div class="input-group mb-3">
                            @Html.TextBox("Fullname", null, new { @class = "form-control", type = "text", placeholder = "Họ và tên" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-user"></span>
                                </div>
                            </div>
                        </div>
                        <label>Ngày sinh</label>
                        <div class="input-group mb-3">
                            @Html.TextBox("Birthday", null, new { @class = "form-control", type = "date", name = "Birthday" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-birthday-cake"></span>
                                </div>
                            </div>
                        </div>
                        @*<label>Giới tính:<text>&nbsp;&nbsp;&nbsp;</text></label>
                            <label class="radio-inline">
                                @Html.RadioButton("Sex", 1) Nam<text>&nbsp;&nbsp;&nbsp;</text>
                            </label>
                            <label class="radio-inline">
                                @Html.RadioButton("Sex", 0) Nữ
                            </label>*@
                        <div class="input-group mb-3">
                            @Html.TextBox("PhoneNumber", null, new { @class = "form-control", type = "number", placeholder = "Số điện thoại" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fas fa-phone"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBox("Email", null, new { @class = "form-control", type = "email", placeholder = "Địa chỉ Email" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.TextBox("Address", null, new { @class = "form-control", placeholder = "Địa chỉ" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-map-marked"></span>
                                </div>
                            </div>
                        </div>
                        <label>Chức vụ</label>
                        <div class="input-group mb-3">
                            @Html.DropDownList("idRole", ViewBag.Loadchucvu as SelectList, new { @class = "form-control" })
                            <div class="input-group-text">
                                <span class="fas fa-briefcase"></span>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.Password("Password", null, new { @class = "form-control", placeholder = "Mật khẩu" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @Html.Password("Password1", null, new { @class = "form-control", placeholder = "Nhập lại mật khẩu" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <!-- /.col -->
                            <div class="col-md-auto">
                                <button type="submit" class="btn btn-primary btn-block">Thêm</button>
                            </div>
                            <!-- /.col -->
                        </div>
                    }
                </div>
            </div>
        </div>
        <aside class="control-sidebar control-sidebar-dark"></aside>
    </section>
</div>